### ISSUE TITLE
Error en el build de Nodegip

### ISSUE THREAD

**Issue by ogomez92** [mvarona/CartasContraLaHumanidad#37]
Hola,
Intento hacer npm install y me sale el siguiente error tanto en Windows como en Linux.

npm ERR! gyp verb check python checking for Python executable "/usr/bin/python3" in the PATH
npm ERR! gyp verb `which` succeeded /usr/bin/python3 /usr/bin/python3
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Parece un error bastante tonto de que falta n paréntesis en algún  lado, podéis mirarlo por favor?

gracias.

**Comment by MarioVarona** [comment]
Hola @ogomez92, perdona el retraso, tenía las notificaciones desactivadas 😓.

Parece que es por un problema de versiones de Python, aparentemente no está encontrando Python3 en el sistema. Como la app usa muchos componentes y librerías de terceros, es fácil que ocurra algo así.

Para eliminar este problema, hemos creado una imagen de Docker de la app. Prueba a [instalar y ejecutar Docker](http://docker.com/products/docker-desktop/), compilar la app con `docker build .` y ejecutar la imagen creada con `docker run -p 8000:8000 -it <sha256>`, donde `<sha2356>` es el hash de la imagen de Docker compilada en el paso previo.

Eso debería resolver el problema.

Gracias!!
